### ISSUE TITLE
Cannot find module elm-svg-generator

### ISSUE THREAD

**Issue by omnibs** [groteck/iconsToElm#1]
Hi! I just tried to use it and got this error:

```
$ npx iconsToElm assets/images
Cannot find module './src/elm-svg-generator.js'
```

Took a peek at the repo and I think you might have forgotten to commit this file.

**Comment by groteck** [comment]
Hi!, Not sure I will take a look today.

Thanks for open the issue.

**Comment by groteck** [comment]
Sorry for the late response but I already remove the import and release a new version of the npm Package with the fix
